### PR TITLE
Update dependencies versions to resolve vunerabilities

### PR DESCRIPTION
**Pull request by nGoline**
I've been getting some vulnerability alerts on GitHub while referencing the version 1.0.0 of this package;
I've performed these changes to stop the alerts. All have been tested and is working well.

### CODE REVIEW

**Comment by callumacrae** [comment]
I don't maintain this anymore, but I'm happy to add you as a collaborator. What's your npm username?

**Comment by nGoline** [comment]
Thank you for that.
It's the same as my Github user: ngoline

Regards.

**Comment by callumacrae** [comment]
have sent invites for both the repo and npm 👍

**Comment by nGoline** [comment]
Just got it, thanks!

**Pull request merged**
